### ISSUE TITLE
Morning session peer to peer review.

### ISSUE THREAD

**Issue by rex-9** [principlebrothers/Leaderboard#4]
### Amazing work

- Styling is epic. ✅ 
- API implementation is flawless. ✅ 
- Structure is really impressive. ✅ 

- We can see you've put a lot of effort into this project. 💯 
- However, there are still things we would like to give you some recommendations. 🤗 
- Please kindly consider the following suggestions. 😄 

### Some improvements that can be made.
- [ ] The score input should accept "number" types only. 
- [ ] The validation of the input should be added for "empty values".

**Comment by principlebrothers** [comment]
Suggestions have been implemented.
